### ISSUE TITLE
JSON-RPC "Player.GetItem" parameter "1" locks EventGhost

### ISSUE THREAD

**Issue by jonisb** [jonisb/KodiEventGhost#6]
"Player.GetItem" parameter "[1]" does not lock up

**Comment by jonisb** [comment]
Doesn't lock up anymore, but gives error:
```
Traceback (most recent call last) (1722):
  File "C:\Program Files (x86)\Util\EventGhost\eg\Classes\TaskletDialog.py", line 59, in ProcessingTask
    self.Configure(*args, **kwargs)
  File "C:\Program Files (x86)\Util\EventGhost\eg\Classes\ConfigDialog.py", line 165, in Configure
    treeItem.Configure(*args)
  File "C:\Program Files (x86)\Util\EventGhost\eg\Classes\ActionItem.py", line 101, in Configure
    return self.executable.Configure(*args)
  File "C:\Program Files (x86)\Util\EventGhost\plugins\XBMCRepeat\__init__.py", line 1369, in Configure
    if 'jsonrpc' in jsonTemp:
TypeError: argument of type 'int' is not iterable
```
